apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: lmoisei/payment-service:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-service:9092
            - name: DB_HOST
              value: pgsql.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: password
            - name: DB_DATABASE
              value: payment
