apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_TOKEN_SECRET: c3VwZXJfc2VjcmV0X2tleQ==  # Replace with your base64 encoded secret
  JWT_REFRESH_TOKEN_SECRET: c3VwZXJfc2VjcmV0X2tleQ==  # Replace with your base64 encoded secret
  JWT_TOKEN_EXPIRATION_EXPIRATION_TIME_SECONDS: MjRo  # Replace with your base64 encoded value
  JWT_REFRESH_TOKEN_EXPIRATION_EXPIRATION_TIME_SECONDS: MTBk  # Replace with your base64 encoded value
