apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: lmoisei/catalog-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-service:9092
            - name: DB_HOST
              value: pgsql.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: password
            - name: DB_DATABASE
              value: catalog
